"""Final classes for the proxy objects on the current server

The classes in Final are generated by the :py:class:`pycraft.server.channel.Channel`
method :py:class:`pycraft.server.channel.Channel.introspect` from information 
provided by the PycraftServer Plugin running inside the Minecraft server.

The classes are, for the most part, wrappers around Bukkit API Interfaces.
"""
